# -*- coding: utf-8 -*-
"""PhanLoaiTinTucTheThao

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oers1HNqBYk2EHCAVCWovlEm13tZIN88
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install underthesea

import pandas as pd

file_path = "/content/drive/MyDrive/LuanAnTotNghiep/PhanLoai.xlsx"
df = pd.read_excel(file_path)

# Xem trước dữ liệu
print(df)

# Hiển thị thông tin cơ bản về DataFrame
print(df.info())

#Kiểm tra null
print(df.isnull().sum())

# Tính số lượng và phần trăm của mỗi nhãn (Phân loại)
label_counts = df['Phân loại'].value_counts()
label_percentages = df['Phân loại'].value_counts(normalize=True) * 100
# Làm tròn phần trăm đến 2 chữ số thập phân
label_percentages = label_percentages.round(2)
# In ra kết quả
print("Số lượng của mỗi nhãn: ", label_counts)
print("\nPhần trăm của mỗi nhãn: ", label_percentages)

# Kiểm tra số lượng dòng dữ liệu bị trùng
duplicate_rows_df = df[df.duplicated()]
print("Số lượng dòng bị trùng: ", duplicate_rows_df.shape)

# Loại bỏ các cột không cần thiết
df = df.drop(columns=['STT', 'Nguồn', 'Link'])
# Kiểm tra lại dữ liệu sau khi loại bỏ cột
print("\nDữ liệu sau khi loại bỏ các cột STT, Nguồn và Link:")
print(df)

# Chuyển đổi văn bản của cột Nội dung, Tiêu đề, Phân loại thành chữ thường
df['Tiêu đề'] = df['Tiêu đề'].str.lower()
df['Nội dung'] = df['Nội dung'].str.lower()
df['Phân loại'] = df['Phân loại'].str.lower()
print (df['Tiêu đề'])
print (df['Nội dung'])
print (df['Phân loại'])

import re

# Hàm loại bỏ ký tự đặc biệt nhưng giữ lại ký tự tiếng Việt có dấu
def remove_special_characters(text):
    if isinstance(text, str):  # Kiểm tra nếu text là chuỗi
        # Giữ lại chữ cái (có dấu hoặc không), số và khoảng trắng
        return re.sub(r'[^a-zA-ZÀ-ỹ0-9\s]', '', text)
    return text  # Trả lại giá trị gốc nếu không phải chuỗi

# Thay thế giá trị NaN bằng chuỗi rỗng và chuyển đổi thành chuỗi
df['Nội dung'] = df['Nội dung'].fillna('').astype(str)
df['Tiêu đề'] = df['Tiêu đề'].fillna('').astype(str)

# Áp dụng hàm loại bỏ ký tự đặc biệt cho các cột
df['Nội dung'] = df['Nội dung'].apply(remove_special_characters)
df['Tiêu đề'] = df['Tiêu đề'].apply(remove_special_characters)

# Xem kết quả
print(df[['Nội dung', 'Tiêu đề']])

#Loại bỏ dấu câu của cột Nội dung và Tiêu đề
df['Nội dung'] = df['Nội dung'].apply(lambda x: re.sub(r'[^\w\s]', '', x))
df['Tiêu đề'] = df['Tiêu đề'].apply(lambda x: re.sub(r'[^\w\s]', '', x))
print (df['Tiêu đề'])
print (df['Nội dung'])

# Hàm loại bỏ khoảng trắng thừa
def remove_extra_whitespace(text):
    if isinstance(text, str):
      # Tách các từ và ghép lại với một khoảng trắng duy nhất giữa các từ
        return ' '.join(text.split())
    return text
# Áp dụng hàm loại bỏ khoảng trắng thừa cho các cột
df['Nội dung'] = df['Nội dung'].apply(remove_extra_whitespace)
df['Tiêu đề'] = df['Tiêu đề'].apply(remove_extra_whitespace)
# Kiểm tra kết quả sau khi loại bỏ khoảng trắng thừa
print(df['Nội dung'])
print(df['Tiêu đề'])

# Biểu đồ tần suất các từ của cột nội dung
import matplotlib.pyplot as plt
from collections import Counter
from nltk.tokenize import word_tokenize
# Tạo danh sách tất cả các từ từ cột 'Nội dung'
all_words = ' '.join(df['Nội dung']).split()
# Đếm tần suất xuất hiện của các từ
word_freq = Counter(all_words)
# Lấy top 20 từ  phổ biến nhất
most_common_keywords = word_freq.most_common(20)
keywords, frequencies = zip(*most_common_keywords)
# Vẽ biểu đồ tần suất các từ
plt.figure(figsize=(12, 6))
plt.barh(keywords, frequencies, color='lightcoral')
plt.xlabel('Số Lần Xuất Hiện')
plt.ylabel('Từ')
plt.title('20 Từ Xuất Hiện Nhiều Nhất Ở Cột Nội Dung')
plt.gca().invert_yaxis()
plt.show()

# Biểu đồ tần suất các từ của cột tiêu đề
import matplotlib.pyplot as plt
from collections import Counter
from nltk.tokenize import word_tokenize
# Tạo danh sách tất cả các từ từ cột 'Tiêu đề'
all_words = ' '.join(df['Tiêu đề']).split()
# Đếm tần suất xuất hiện của các từ
word_freq = Counter(all_words)
# Lấy top 20 từ  phổ biến nhất
most_common_keywords = word_freq.most_common(20)
keywords, frequencies = zip(*most_common_keywords)
# Vẽ biểu đồ tần suất các từ
plt.figure(figsize=(12, 6))
plt.barh(keywords, frequencies, color='lightcoral')
plt.xlabel('Số Lần Xuất Hiện')
plt.ylabel('Từ')
plt.title('20 Từ Xuất Hiện Nhiều Nhất Ở Cột Tiêu Đề')
plt.gca().invert_yaxis()
plt.show()

from underthesea import word_tokenize
with open("/content/drive/MyDrive/LuanAnTotNghiep/vietnamese-stopwords.txt", "r", encoding="utf-8") as f:
    vietnamese_stopwords = set(f.read().splitlines())
# Hàm loại bỏ stopwords tiếng Việt
def remove_vietnamese_stopwords(text):
    if isinstance(text, str):
        text = text.lower()  # Chuyển thành chữ thường
        tokens = word_tokenize(text)  # Tách từ
        filtered_tokens = [word.replace("_", " ") for word in tokens if word not in vietnamese_stopwords]  # Thay _ bằng dấu cách
        return ' '.join(filtered_tokens)  # Giữ khoảng cách giữa các từ
    return text

# Áp dụng hàm loại bỏ stopwords
df['Nội dung'] = df['Nội dung'].apply(remove_vietnamese_stopwords)
df['Tiêu đề'] = df['Tiêu đề'].apply(remove_vietnamese_stopwords)

# Kiểm tra kết quả
print(df['Nội dung'])
print(df['Tiêu đề'])

# Biểu đồ tần suất các từ khóa của cột Nội dung sau khi loại bỏ stopwords
import matplotlib.pyplot as plt
from collections import Counter
from nltk.tokenize import word_tokenize
# Tạo danh sách tất cả các từ từ cột 'Nội dung'
all_words = ' '.join(df['Nội dung']).split()
# Đếm tần suất xuất hiện của các từ
word_freq = Counter(all_words)
# Lấy top 20 từ khóa phổ biến nhất
most_common_keywords = word_freq.most_common(20)
keywords, frequencies = zip(*most_common_keywords)
# Vẽ biểu đồ tần suất các từ khóa
plt.figure(figsize=(12, 6))
plt.barh(keywords, frequencies, color='yellow')
plt.xlabel('Số Lần Xuất Hiện')
plt.ylabel('Từ')
plt.title('20 Từ Xuất Hiện Nhiều Nhất Ở Cột Nội Dung Sau Khi Loại Bỏ Stopwords')
plt.gca().invert_yaxis()
plt.show()

# Biểu đồ tần suất các từ khóa của cột Tiêu đề sau khi loại bỏ stopwords
import matplotlib.pyplot as plt
from collections import Counter
from nltk.tokenize import word_tokenize
# Tạo danh sách tất cả các từ từ cột 'Tiêu đề'
all_words = ' '.join(df['Tiêu đề']).split()
# Đếm tần suất xuất hiện của các từ
word_freq = Counter(all_words)
# Lấy top 20 từ khóa phổ biến nhất
most_common_keywords = word_freq.most_common(20)
keywords, frequencies = zip(*most_common_keywords)
# Vẽ biểu đồ tần suất các từ khóa
plt.figure(figsize=(12, 6))
plt.barh(keywords, frequencies, color='yellow')
plt.xlabel('Số Lần Xuất Hiện')
plt.ylabel('Từ')
plt.title('20 Từ Xuất Hiện Nhiều Nhất Ở Cột Tiêu Đề Sau Khi Loại Bỏ Stopwords')
plt.gca().invert_yaxis()
plt.show()

# Tính độ dài của văn bản trong các cột 'Nội dung' và 'Tiêu đề'
df['Độ dài Nội dung'] = df['Nội dung'].apply(lambda x: len(str(x).split()))
df['Độ dài Tiêu đề'] = df['Tiêu đề'].apply(lambda x: len(str(x).split()))
# Xem kết quả
print(df[['Độ dài Nội dung', 'Độ dài Tiêu đề']])

# Tìm độ dài lớn nhất và nhỏ nhất của 'Nội dung'
max_noidung = df['Độ dài Nội dung'].max()
min_noidung = df['Độ dài Nội dung'].min()

# Tìm độ dài lớn nhất và nhỏ nhất của 'Tiêu đề'
max_tieude = df['Độ dài Tiêu đề'].max()
min_tieude = df['Độ dài Tiêu đề'].min()

# Xuất kết quả
print(f"Độ dài Nội dung lớn nhất: {max_noidung}, nhỏ nhất: {min_noidung}")
print(f"Độ dài Tiêu đề lớn nhất: {max_tieude}, nhỏ nhất: {min_tieude}")

# Biểu đồ phân phối độ dài văn bản trong cột Nội dung
plt.figure(figsize=(14, 6))
plt.subplot(1, 2, 1)
plt.hist(df['Độ dài Nội dung'], bins=30, color='skyblue', edgecolor='black')
plt.xlabel('Số Lượng Từ Trong Cột Nội Dung')
plt.ylabel('Số Lần Xuất Hiện')
plt.title('Biểu Đồ Phân Phối Độ Dài Văn Bản Trong Cột Nội Dung')

# Biểu đồ phân phối độ dài văn bản trong cột Tiêu đề
plt.subplot(1, 2, 2)
plt.hist(df['Độ dài Tiêu đề'], bins=18, color='salmon', edgecolor='black')
plt.xlabel('Số Lượng Từ Trong Cột Tiêu Đề')
plt.ylabel('Số Lần Xuất Hiện')
plt.title('Biểu Đồ Phân Phối Độ Dài Văn Bản Trong Cột Tiêu Đề')
plt.tight_layout()
plt.show()

from underthesea import word_tokenize

# Hàm tokenize & làm sạch (trả về danh sách từ)
def tokenize_words(text):
    if isinstance(text, str):
        tokens = word_tokenize(text)  # Tách từ
        clean_tokens = [word.replace("_", " ") for word in tokens]  # Thay dấu gạch dưới
        return clean_tokens  # Trả về danh sách từ
    return []

# Áp dụng cho cột 'Nội dung' và 'Tiêu đề'
df['Nội dung Tokenize'] = df['Nội dung'].apply(tokenize_words)
df['Tiêu đề Tokenize'] = df['Tiêu đề'].apply(tokenize_words)

# In kết quả
print(df[['Nội dung Tokenize', 'Tiêu đề Tokenize']])

import pandas as pd
from tensorflow.keras.preprocessing.text import Tokenizer

# Khởi tạo Tokenizer
tokenizer = Tokenizer(num_words=20000, oov_token="<OOV>")  # Giới hạn 20,000 từ, xử lý từ ngoài từ điển bằng "<OOV>"

# Nối Tiêu đề và Nội dung thành một văn bản duy nhất
df['Kết hợp'] = df['Tiêu đề Tokenize'].astype(str) + " " + df['Nội dung Tokenize'].astype(str)

# Fitting Tokenizer trên văn bản kết hợp
tokenizer.fit_on_texts(df['Kết hợp'])

# Chuyển văn bản thành số
df['X_sequences'] = tokenizer.texts_to_sequences(df['Kết hợp'])

# In 10 dòng đầu tiên để kiểm tra
print(df[['Kết hợp', 'X_sequences']])

df['Độ dài Kết hợp'] = df['Kết hợp'].apply(lambda x: len(str(x).split()))
# Tìm độ dài lớn nhất và nhỏ nhất của 'Kết hợp'
max_kethop = df['Độ dài Kết hợp'].max()
min_kethop = df['Độ dài Kết hợp'].min()
# Xuất kết quả
print(f"Độ dài Kết hợp lớn nhất: {max_kethop}, nhỏ nhất: {min_kethop}")

# Chuyển nhãn phân loại từ dạng văn bản sang số
df['y_encoded'] = df['Phân loại'].astype('category').cat.codes

# In kết quả
print(df[['Phân loại', 'y_encoded']].drop_duplicates())  # Xem nhãn gốc và số tương ứng

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Chuyển danh sách từ thành chuỗi để Tokenizer xử lý
df['Nội dung Tokenize Str'] = df['Nội dung Tokenize'].apply(lambda x: " ".join(x))
df['Tiêu đề Tokenize Str'] = df['Tiêu đề Tokenize'].apply(lambda x: " ".join(x))

# Gộp cả tiêu đề & nội dung để huấn luyện Tokenizer
texts = df['Tiêu đề Tokenize Str'] + " " + df['Nội dung Tokenize Str']

# Khởi tạo Tokenizer
tokenizer = Tokenizer(num_words=5000, oov_token="<OOV>")  # Chỉ lấy 20,000 từ phổ biến nhất
tokenizer.fit_on_texts(texts)

# Chuyển văn bản thành số
X_sequences = tokenizer.texts_to_sequences(texts)

# Padding để có độ dài cố định (giả sử max_length = 360)
max_length = 360
X_padded = pad_sequences(X_sequences, maxlen=max_length, padding='post', truncating='post')

# Kiểm tra kết quả
print(X_padded.shape)  # Kích thước đầu ra của dữ liệu đã padding
print(X_padded)  # Xem 5 dòng đầu tiên
df['X_padded'] = list(X_padded)

#LSTM
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, SpatialDropout1D, Bidirectional
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import classification_report
# Xác định X và y
X = df["Kết hợp"].astype(str).tolist()
y = df["y_encoded"].values
# Tokenizer
vocab_size = 8096
tokenizer = Tokenizer(num_words=vocab_size, oov_token="<OOV>")
tokenizer.fit_on_texts(X)
# Chuyển văn bản thành số
X_sequences = tokenizer.texts_to_sequences(X)
# Xử lý độ dài cố định
max_len = 360
X_padded = pad_sequences(X_sequences, maxlen=max_len, padding='post', truncating='post')
# Chia tập train/test
X_train, X_test, y_train, y_test = train_test_split(X_padded, y, test_size=0.2, random_state=42, stratify=y)
# Chuyển y thành one-hot encoding
num_classes = len(np.unique(y))
y_train_one_hot = to_categorical(y_train, num_classes=num_classes)
y_test_one_hot = to_categorical(y_test, num_classes=num_classes)
# Xử lý mất cân bằng dữ liệu bằng class weights
class_weights = compute_class_weight(class_weight="balanced", classes=np.unique(y), y=y)
class_weights_dict = {i: weight for i, weight in enumerate(class_weights)}
# Xây dựng mô hình tối ưu hơn
model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=200, input_length=max_len),  # Giảm chiều embedding
    SpatialDropout1D(0.3),
    Bidirectional(LSTM(64, return_sequences=True, dropout=0.2, recurrent_dropout=0.1)),
    Bidirectional(LSTM(32, dropout=0.2)),
    Dense(32, activation='relu'),
    Dropout(0.3),
    Dense(num_classes, activation='softmax')
])
# Compile mô hình
model.compile(loss='categorical_crossentropy', optimizer=Adam(learning_rate=0.0005), metrics=['accuracy'])
# Callbacks
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.3, patience=2, min_lr=1e-6)
# Huấn luyện mô hình với class weights
history_lstm = model.fit(X_train, y_train_one_hot,
                    validation_split=0.2,
                    epochs=20,  # Giảm số epoch
                    batch_size=64,  # Tăng batch size để tăng tốc độ
                    class_weight=class_weights_dict,
                    callbacks=[reduce_lr])
# Dự đoán trên tập test
y_pred_probs = model.predict(X_test)
y_pred = np.argmax(y_pred_probs, axis=1)
y_true = np.argmax(y_test_one_hot, axis=1)
# In báo cáo phân loại
print(classification_report(y_true, y_pred))

import matplotlib.pyplot as plt

unique, counts = np.unique(y_test, return_counts=True)
plt.bar(unique, counts)
plt.xlabel("Nhãn")
plt.ylabel("Số Lượng")
plt.title("Phân Phối Nhãn Trong Bộ Kiểm Tra")
plt.show()

#CNN
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Conv1D, GlobalMaxPooling1D, Dense, Dropout
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import classification_report
import numpy as np
# Xác định X và y
X = df["Kết hợp"].astype(str).tolist()
y = df["y_encoded"].values
# THÔNG SỐ CƠ BẢN
vocab_size = 8096  # Kích thước từ vựng
max_len = 360  # Độ dài tối đa của mỗi câu
embedding_dim = 128  # Kích thước vector nhúng
num_classes = y_train_one_hot.shape[1]  # Số lớp phân loại
# XÂY DỰNG MÔ HÌNH CNN
model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len),
    Conv1D(128, kernel_size=5, activation='relu'),
    GlobalMaxPooling1D(),
    Dense(64, activation='relu'),
    Dropout(0.5),
    Dense(num_classes, activation='softmax')
])
# COMPILATION & TRAINING
model.compile(loss='categorical_crossentropy', optimizer=Adam(learning_rate=0.0003), metrics=['accuracy'])
history_cnn = model.fit(X_train, y_train_one_hot, validation_data=(X_test, y_test_one_hot), epochs=20, batch_size=32)
# DỰ ĐOÁN & ĐÁNH GIÁ
y_pred_probs = model.predict(X_test)
y_pred = np.argmax(y_pred_probs, axis=1)
y_true = np.argmax(y_test_one_hot, axis=1)
print(classification_report(y_true, y_pred))

#GRU
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GRU, Dense, Dropout, Bidirectional
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import classification_report
import numpy as np
vocab_size = 8096
max_len = 360
embedding_dim = 64
gru_units = 64
num_classes = y_train_one_hot.shape[1]
#Mô hình GRU
model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len),
    Bidirectional(GRU(gru_units, return_sequences=False, dropout=0.2)),  # Giảm 1 tầng GRU
    Dense(32, activation='relu'),
    Dropout(0.3),
    Dense(num_classes, activation='softmax')
])
#Training
model.compile(loss='categorical_crossentropy', optimizer=Adam(learning_rate=0.001), metrics=['accuracy'])
history_gru = model.fit(X_train, y_train_one_hot, validation_data=(X_test, y_test_one_hot), epochs=20, batch_size=64)
#Đánh giá mô hình
y_pred_probs = model.predict(X_test)
y_pred = np.argmax(y_pred_probs, axis=1)
y_true = np.argmax(y_test_one_hot, axis=1)
print(classification_report(y_true, y_pred))

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Dropout
#THÔNG SỐ MÔ HÌNH
vocab_size = 8096
max_len = 360  # Giảm max_len để tăng tốc
embedding_dim = 128
num_classes = y_train_one_hot.shape[1]
#XÂY DỰNG MÔ HÌNH Bi-LSTM
model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len),
    Bidirectional(LSTM(64, return_sequences=False)),  # Giảm số đơn vị LSTM & bỏ return_sequences
    Dropout(0.3),  # Giảm dropout để tránh mất quá nhiều thông tin
    Dense(32, activation='relu'),  # Giảm số neuron
    Dropout(0.3),
    Dense(num_classes, activation='softmax')
])
#COMPILATION & TRAINING
model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.Adam(learning_rate=0.0003), metrics=['accuracy'])
history_bilstm = model.fit(X_train, y_train_one_hot, validation_data=(X_test, y_test_one_hot), epochs=20, batch_size=64)
#DỰ ĐOÁN & ĐÁNH GIÁ
y_pred_probs = model.predict(X_test)
y_pred = tf.argmax(y_pred_probs, axis=1).numpy()
y_true = tf.argmax(y_test_one_hot, axis=1).numpy()
from sklearn.metrics import classification_report
print(classification_report(y_true, y_pred))